version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo just pretend we did something!
artifacts:
  files:
    - "**/*"
  base-directory: dist
